# Python Basics

 ## $\color{red}{\text{Objects}}$

The Python library consists of all core elements, such as data types and built-in functions but the bulk of the Python library consists of modules. In order for you to be able to make use of modules in your own code, you first need to import those modules using the import statement.

Let's first import a library called **NumPy**, which will be imported as **np** and this is just to save me some typing. 

In [10]:
#Importing Numpy
import numpy as np

 Two arrays, $x$ and $y$, of three numbers will be defined. 

In [11]:
#Define array x
x = np.array([1,3,5])

#Define array y
y = np.array([1,5,9])

Now both of these objects are NumPy arrays. That means they both support the same methods and have the same attributes available.

### $\color{blue}{\text{Methods}}$ 
To know the mean of the numbers in $x$, you would simply ask Python to return that. Here, the mean method will be called, which is connected to the object $x$. I can do the same exact thing for object $y$. They turn out to have different means in this case, but in both cases the mean method is available to use for both.

In [12]:
#Calculate the mean of array x
x.mean()

3.0

In [13]:
#Calculate the mean of array y
y.mean()

5.0

### $\color{blue}{\text{Data Attributes}}$ 
Let's look at an example of a data attribute. If I type $x$.shape, Python is telling me that this array contains three numbers. Similarly, this can be done for object $y$ where there are three elements embedded in it.

In [14]:
#Find out the shape of array x (i.e., how many rows and columns it contains)
x.shape

(3,)

In [15]:
#Find out the shape of array y (i.e., how many rows and columns it contains)
y.shape

(3,)

$\color{Green}{\text{NB}}$: Notice in the first case, when Python was asked to compute a value, two parentheses were following the name of the attribute. That means **mean** is a function (or a method). In contrast, when Python was asked to return the shape of the array, no parentheses were following the word shape. That means **shape** is a data attribute.

 ## $\color{red}{\text{Modules and Methods}}$

In [16]:
#Importing "math" module
import math

In [17]:
#Choosing only "pi" method from "math" mdoule
from math import pi

In [19]:
#To list all the methods (functions) availble in the given module
dir(math)

# Scalars, Vectors and Matrices

##  $\color{red}{\text{Scalars}}$
A scalar is a single number. For example temperature, distance, speed, or mass – all these quantities have a magnitude and can be defined as a single number. 

In [32]:
#Integers and float numbers
x = 2 #Define an integer
y = 2.5 #Define a float
#Basic Operations
display(x+y)  #Addition
display(y-x)  #Subtraction
display(x*y)  #Multiplication
display(x/y)  #Division
display(x//y) #Floor division
display(x**y) #Exponentiation

#Importing "cmath" for complex number operations
import cmath
# Initializing real numbers
x = 5
y = 3
# converting x and y into complex number
z = complex(x,y);
# display the real and imaginary part of complex number
display(z.real)
display(z.imag)


4.5

0.5

5.0

0.8

0.0

5.656854249492381

2.0

5.0

3.0

##  $\color{red}{\text{Vectors}}$
A vector is an array of numbers. A vector is an arrow representing a quantity that has both magnitude and direction wherein the length of the arrow represents the magnitude and the orientation tells you the direction. For example wind, which has a direction and magnitude.

In [1]:
#Import numpy package
import numpy as np

In [12]:
#Equivalent ways to create a row vector
x1 = np.array([1,2,3])
x2 = np.matrix([1,2,3])

display(x1) #show vector x1
display(x2) #show vector x2


array([1, 2, 3])

matrix([[1, 2, 3]])

In [13]:
#Equivalent ways to create a column vector
y1 = np.array([[1],[2],[3]]) # notice that each row is in square brackets
y2 = np.matrix([[1],[2],[3]])

display(y1) #show vector y2
display(y2) #show vector y3

array([[1],
       [2],
       [3]])

matrix([[1],
        [2],
        [3]])

In [14]:
#Create a vector within a range [a,b], where a is the start of the range, and b is the end+1.
z1 = np.arange(0,10) #0 is the start, and 10 is the end+1
z2 = np.arange(0,10,1) #0 is the start, 10 is the end+1, 1 is the step taken between each value.
z3 = np.arange(0,9,2) #0 is the start, 9 is the end+1, 2 is the step taken between each value.

display(z1) #show vector z1
display(z2) #show vector z2
display(z3) #show vector z3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

##  $\color{red}{\text{Matrices}}$
A matrix is a $2$D array. In other words, a matrix is a collection of $m$ rows (its height) and $n$ columns (its width) of data.

In [17]:
#Create a 3x3 matrix: 3 rows and 3 columns
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

display(A) #show matrix A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Accessing and manipulating matrix rows, columns and elements
a1 = A[1,2] #access the element in the 2nd row and 3rd column
a2 = A[1,:] #access 2nd row with all its elements/columns (the colon (:) means access everything in that row)
a3 = A[:,2] #access 3rd column with all its elements/rows (the colon (:) means access everything in that column)

display(a1) #show a1
display(a2) #show a2
display(a3) #show a3

6

array([4, 5, 6])

array([3, 6, 9])

In [29]:
#Describing matrices
display(A.shape) #show the number of rows and columns

display(A.size) #show the number of elements (rows*columns)

display(A.ndim) #show the number of dimensions

(3, 3)

9

2

In [25]:
#Matrix operations
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Define matrix A
B = np.array([[10,11,12],[13,14,15],[16,17,28]]) #Define matrix B

#Addition
Add1 = A+B
Add2 = np.add(A,B)

display(Add1)
display(Add2)

#Subtraction
Sub1 = A-B
Sub2 = np.subtract(A,B)

display(Sub1)
display(Sub2)

#Transpose
AT = A.T #Take the transpose of matrix A
BT = B.T #Take the transpose of matrix B

display(AT)
display(BT)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 37]])

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 37]])

array([[ -9,  -9,  -9],
       [ -9,  -9,  -9],
       [ -9,  -9, -19]])

array([[ -9,  -9,  -9],
       [ -9,  -9,  -9],
       [ -9,  -9, -19]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 28]])

# Problem: Work

Work ($W$ (J)) is the transfer of energy by a force ($\vec{\bf{F}}$ (N)) acting on an object as it is moved from one place to another- that is, undergoes a displacement ($\vec{\bf{s}}$ (m)). You do more work if the force or the displacement is greater. Mathematically, we define the work done by a constant force as the dot product of the force and displacement vectors:

\begin{equation}
    W = \vec{\bf{F}} \cdot \vec{\bf{s}} = |\vec{\bf{F}}| |\vec{\bf{s}}| \cos \phi \quad \quad \quad \mathrm{and} \quad \quad \quad W = \vec{\bf{F}} \cdot \vec{\bf{s}} = F_x s_x + F_y s_y + F_z s_z
    \label{WorkDotProduct}
\end{equation}

Think of a person exerting a force on a stalled car of magnitude $210$ N as he pushes it in a distance of $18$ m. The car has also a flat tire, so to make the car track straight, the person needs to push at an angle of $30^o$ to the direction of the motion. How much work does thsis person do?

In [52]:
#import numpy library
import numpy as np

#Define input values
F = 210 # force magnitude in N
s = 18 # displacement magnitude in m
#phi = (np.pi)/6 #angle in radians between the force and the displacement vectors (30 deg)
phi = 30*(np.pi/180) #or transform the angle from degrees to radians

#Calculate work
W = F*s*(np.cos(phi)) #in J


3273.5760263051784

This person needs to push a second stalled car with a steady force $ \vec{\bf{F}}=(160 \mathrm{N}) \hat{\textit{i}} - (40 \mathrm{N}) \hat{\textit{j}}$. The displacement of the car is $\vec{\bf{s}}=(14 \mathrm{m})\hat{\textit{i}} +(11 \mathrm{m}) \hat{\textit{j}}$. How much work does this person do?

In [55]:
#import numpy library
import numpy as np

#Define the vectors
F = np.array([160 , -40]) #Force vector
s = np.array([14 , 11]) #displacement vector

#Calculate the sum of the products of their respective components
W = F[0]*s[0] + F[1]*s[1] #in J



Supoose we have the following two vectors:

$$
\vec{\bf{F}}=2 \hat{\textit{i}}+3\hat{\textit{j}}+1\hat{\textit{k}} \quad \quad \quad \mathrm{and} \quad \quad \quad \vec{\bf{s}}=-4 \hat{\textit{i}}+2\hat{\textit{j}}-1\hat{\textit{k}}
$$

To Calculate the angle between them, we use the equation:

$$
\cos \phi = \frac{\vec{\bf{F}}\cdot \vec{\bf{s}}}{|\vec{\bf{F}}| |\vec{\bf{s}}|} = \frac{F_x s_x + F_y s_y + F_z s_z}{|\vec{\bf{F}}| |\vec{\bf{s}}|} = \frac{F_x s_x + F_y s_y + F_z s_z}{\sqrt{F_x^2+ F_y^2 + F_z^2} \sqrt{s_x^2+ s_y^2 + s_z^2}}
$$

In [58]:
#import numpy
import numpy as np

#Define the vectors
F = np.array([2,3,1])
s = np.array([-4,2,-1])

#Calculate the sum of the products of their respective components
FTimess = F[0]*s[0] + F[1]*s[1] + F[2]*s[2]

#Calculate their magnitudes
#Vector F
Fsquare = np.square(F) #the square of each component of vector F
Fsum    = np.sum(Fsquare) #the sum of the squared components of F
Fmag    = np.sqrt(Fsum) #square root of the sum
#Vector s
ssquare = np.square(s) #the square of each component of vector s
ssum    = np.sum(ssquare) #the sum of the squared components of s
smag    = np.sqrt(ssum) #square root of the sum

#Calculate the cosine of the angle
CosinePhi = FTimess / (Fmag * smag)

#Calculate the angle (inverse of the cosine)
Phi_rad = np.arccos(CosinePhi) #in radians
Phi_deg = Phi_rad*(180/np.pi) #in degrees

#We notice here that the work is negative and the angle is between 90 and 180. This means ...

-3

# Booleans

Expression is a combination of objects and operators that computes a value. Many expressions involve what is known as the boolean data type. Objects of the boolean type have only two values. These are called True and False.

##  $\color{red}{\text{True and False}}$

In [2]:
type(True)

bool

In [3]:
type(False)

bool

In [4]:
type(false)

NameError: name 'false' is not defined

##  $\color{red}{\text{Comparison Operators}}$

In [5]:
x = 10
y = 12

# Output: x > y is False
print('x > y is',x>y)

# Output: x < y is True
print('x < y is',x<y)

# Output: x == y is False
print('x == y is',x==y)

# Output: x != y is True
print('x != y is',x!=y)

# Output: x >= y is False
print('x >= y is',x>=y)

# Output: x <= y is True
print('x <= y is',x<=y)

x > y is False
x < y is True
x == y is False
x != y is True
x >= y is False
x <= y is True


##  $\color{red}{\text{Logical Operators}}$

In [6]:
x = True
y = False

# Output: x and y is False
print('x and y is',x and y)

# Output: x or y is True
print('x or y is',x or y)

# Output: not x is False
print('not x is',not x)

x and y is False
x or y is True
not x is False


##  $\color{red}{\text{Identity Operators}}$

In [8]:
x1 = 5
y1 = 5
x2 = 'Hello'
y2 = 'Hello'
x3 = [1,2,3]
y3 = [1,2,3]
z3 = y3

# Output: False
print(x1 is not y1)

# Output: True
print(x2 is y2)

# Output: False
print(x3 is y3)

# Output: True
print(z3 is y3)

False
True
False
True
